In [ ]:
import pandas as pd
import numpy as np

from sklearn.metrics import (
    classification_report,
    accuracy_score,
    confusion_matrix,
    ConfusionMatrixDisplay
)

from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

In [ ]:
# ============================================================
# LOAD DATA
# ============================================================

df = pd.read_csv(
    "/Users/ayushparoha/Downloads/sml/ass3/medicinal drug dataset.csv"
)

print(df.head())

print("\nDataset Information:")
df.info()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [ ]:
# ============================================================
# TARGET VARIABLE: DRUG
# ============================================================

print("\nDrug class distribution:")
print(df["Drug"].value_counts())

print("\nPercentage:")
print(df["Drug"].value_counts(normalize=True) * 100)


# Encode target variable
le_drug = LabelEncoder()

y = le_drug.fit_transform(df["Drug"])

print("\nDrug classes:")
print(le_drug.classes_)


Drug class distribution:
Drug
DrugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: count, dtype: int64

Percentage:
Drug
DrugY    45.5
drugX    27.0
drugA    11.5
drugC     8.0
drugB     8.0
Name: proportion, dtype: float64

Drug classes:
['DrugY' 'drugA' 'drugB' 'drugC' 'drugX']


In [ ]:
# ============================================================
# ATTEMPT 1
# NAIVE BAYES WITHOUT CATEGORICAL DATA
# ============================================================

print("\n" + "=" * 60)
print("ATTEMPT 1 - WITHOUT CATEGORICAL DATA")
print("=" * 60)


ATTEMPT 1 - WITHOUT CATEGORICAL DATA


In [ ]:
# Only numerical features
X1 = df[["Age", "Na_to_K"]].values

print("\nFeature matrix shape:")
print(X1.shape)


# Train-test split
X1_train, X1_test, y_train, y_test = train_test_split(
    X1,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


Feature matrix shape:
(200, 2)


In [ ]:
# Standardization
sc1 = StandardScaler()

X1_train = sc1.fit_transform(X1_train)
X1_test = sc1.transform(X1_t

SyntaxError: incomplete input (<ipython-input-6-76ea6c412833>, line 5)

In [ ]:
# Standardization
sc1 = StandardScaler()

X1_train = sc1.fit_transform(X1_train)
X1_test = sc1.transform(X1_test)

In [ ]:
# Gaussian Naive Bayes
clf1 = GaussianNB()

clf1.fit(X1_train, y_train)

,priors,None
,var_smoothing,1e-09


In [ ]:
# Prediction
y_pred1 = clf1.predict(X1_test)


# Accuracy
acc1 = accuracy_score(y_test, y_pred1)

print(f"\nAttempt 1 Accuracy: {acc1 * 100:.2f}%")


Attempt 1 Accuracy: 75.00%


In [ ]:
# Classification report
print("\nClassification Report - Attempt 1:")

print(
    classification_report(
        y_test,
        y_pred1,
        target_names=le_drug.classes_
    )
)


Classification Report - Attempt 1:
              precision    recall  f1-score   support

       DrugY       0.95      1.00      0.97        18
       drugA       0.00      0.00      0.00         5
       drugB       0.75      1.00      0.86         3
       drugC       0.00      0.00      0.00         3
       drugX       0.53      0.82      0.64        11

    accuracy                           0.75        40
   macro avg       0.45      0.56      0.49        40
weighted avg       0.63      0.75      0.68        40



/Users/ayushparoha/Downloads/sml/env/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/ayushparoha/Downloads/sml/env/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/ayushparoha/Downloads/sml/env/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{me

In [ ]:
# ============================================================
# ATTEMPT 2
# NAIVE BAYES INCLUDING CATEGORICAL DATA
# ============================================================

print("\n" + "=" * 60)
print("ATTEMPT 2 - INCLUDING CATEGORICAL DATA")
print("=" * 60)


# Make a copy
df_enc = df.copy()


ATTEMPT 2 - INCLUDING CATEGORICAL DATA


In [ ]:
# ------------------------------------------------------------
# Encode categorical columns
# ------------------------------------------------------------

# Find categorical columns
categorical_columns = df_enc.select_dtypes(
    include=["object", "category"]
).columns

print("\nCategorical columns:")
print(categorical_columns)


Categorical columns:
Index(['Sex', 'BP', 'Cholesterol', 'Drug'], dtype='object')


In [ ]:
# Encode each categorical column separately
for col in categorical_columns:

    # Don't encode Drug because it is our target
    if col != "Drug":

        le = LabelEncoder()

        df_enc[col] = le.fit_transform(df_enc[col])


print("\nEncoded dataset:")
print(df_enc.head())


Encoded dataset:
   Age  Sex  BP  Cholesterol  Na_to_K   Drug
0   23    0   0            0   25.355  DrugY
1   47    1   1            0   13.093  drugC
2   47    1   1            0   10.114  drugC
3   28    0   2            0    7.798  drugX
4   61    0   1            0   18.043  DrugY


In [ ]:
# ------------------------------------------------------------
# Create X2 and y
# ------------------------------------------------------------

# Remove target column
X2 = df_enc.drop(columns="Drug")

# Convert DataFrame to NumPy AFTER encoding
X2 = X2.values

print("\nX2 shape:")
print(X2.shape)


X2 shape:
(200, 5)


In [ ]:
# ------------------------------------------------------------
# Train-test split
# ------------------------------------------------------------

X2_train, X2_test, y_train, y_test = train_test_split(
    X2,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
# ------------------------------------------------------------
# Standardization
# ------------------------------------------------------------

sc2 = StandardScaler()

X2_train = sc2.fit_transform(X2_train)
X2_test = sc2.transform(X2_test)

In [ ]:
# Gaussian Naive Bayes
# ------------------------------------------------------------

clf2 = GaussianNB()

clf2.fit(X2_train, y_train)


# Prediction
y_pred2 = clf2.predict(X2_test)


# Accuracy
acc2 = accuracy_score(y_test, y_pred2)

print(f"\nAttempt 2 Accuracy: {acc2 * 100:.2f}%")


Attempt 2 Accuracy: 87.50%


In [ ]:
print("\nClassification Report - Attempt 2:")

print(
    classification_report(
        y_test,
        y_pred2,
        target_names=le_drug.classes_
    )
)


Classification Report - Attempt 2:
              precision    recall  f1-score   support

       DrugY       0.93      0.78      0.85        18
       drugA       1.00      1.00      1.00         5
       drugB       0.75      1.00      0.86         3
       drugC       0.50      1.00      0.67         3
       drugX       1.00      0.91      0.95        11

    accuracy                           0.88        40
   macro avg       0.84      0.94      0.86        40
weighted avg       0.91      0.88      0.88        40



In [ ]:
# ATTEMPT 3
# DIFFERENT VAR_SMOOTHING VALUES
# ============================================================

print("\n" + "=" * 60)
print("ATTEMPT 3 - VARIANCE SMOOTHING")
print("=" * 60)


ATTEMPT 3 - VARIANCE SMOOTHING


In [ ]:
# Different smoothing values
smoothing_values = [
    1e-9,
    1e-7,
    1e-5,
    1e-3,
    0.01,
    0.1,
    1.0
]

In [ ]:
print(f"{'var_smoothing':<20} {'Accuracy':>10}")
print("-" * 32)


best_accuracy = 0
best_vs = None

var_smoothing          Accuracy
--------------------------------


In [ ]:
for vs in smoothing_values:

    # Create model
    clf_vs = GaussianNB(
        var_smoothing=vs
    )

    # Train
    clf_vs.fit(
        X2_train,
        y_train
    )

    # Predict
    y_pred_vs = clf_vs.predict(
        X2_test
    )

    # Accuracy
    acc_vs = accuracy_score(
        y_test,
        y_pred_vs
    )

    print(
        f"{vs:<20} {acc_vs * 100:>9.2f}%"
    )


    # Find best value
    if acc_vs > best_accuracy:

        best_accuracy = acc_vs
        best_vs = vs

1e-09                    87.50%
1e-07                    87.50%
1e-05                    95.00%
0.001                    97.50%
0.01                     97.50%
0.1                      92.50%
1.0                      77.50%


In [ ]:
print("\n" + "=" * 60)
print("BEST MODEL")
print("=" * 60)


BEST MODEL


In [ ]:
print(f"\nBest var_smoothing: {best_vs}")
print(f"Best Accuracy: {best_accuracy * 100:.2f}%")


Best var_smoothing: 0.001
Best Accuracy: 97.50%


In [ ]:
# Train final model using best smoothing
clf3 = GaussianNB(
    var_smoothing=best_vs
)

clf3.fit(
    X2_train,
    y_train
)


# Prediction
y_pred3 = clf3.predict(
    X2_test
)


# Accuracy
acc3 = accuracy_score(
    y_test,
    y_pred3
)

print(
    f"\nAttempt 3 Accuracy: {acc3 * 100:.2f}%"
)


Attempt 3 Accuracy: 97.50%


In [ ]:
# Classification report
print("\nClassification Report - Attempt 3:")

print(
    classification_report(
        y_test,
        y_pred3,
        target_names=le_drug.classes_
    )
)


Classification Report - Attempt 3:
              precision    recall  f1-score   support

       DrugY       0.95      1.00      0.97        18
       drugA       1.00      1.00      1.00         5
       drugB       1.00      1.00      1.00         3
       drugC       1.00      1.00      1.00         3
       drugX       1.00      0.91      0.95        11

    accuracy                           0.97        40
   macro avg       0.99      0.98      0.99        40
weighted avg       0.98      0.97      0.97        40



In [ ]:
print("\n" + "=" * 60)
print("CONFUSION MATRICES")
print("=" * 60)


# Attempt 1
cm1 = confusion_matrix(
    y_test,
    y_pred1
)

print("\nConfusion Matrix - Attempt 1:")
print(cm1)


CONFUSION MATRICES

Confusion Matrix - Attempt 1:
[[18  0  0  0  0]
 [ 0  0  0  0  5]
 [ 0  0  3  0  0]
 [ 0  0  0  0  3]
 [ 1  0  1  0  9]]


In [ ]:
# Attempt 2
cm2 = confusion_matrix(
    y_test,
    y_pred2
)

print("\nConfusion Matrix - Attempt 2:")
print(cm2)


Confusion Matrix - Attempt 2:
[[14  0  1  3  0]
 [ 0  5  0  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0  3  0]
 [ 1  0  0  0 10]]


In [ ]:
# Attempt 3
cm3 = confusion_matrix(
    y_test,
    y_pred3
)

In [ ]:
print("\nConfusion Matrix - Attempt 3:")
print(cm3)


Confusion Matrix - Attempt 3:
[[18  0  0  0  0]
 [ 0  5  0  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0  3  0]
 [ 1  0  0  0 10]]
